version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y unzip
      - curl "https://releases.hashicorp.com/terraform/1.5.3/terraform_1.5.3_linux_amd64.zip" -o "terraform.zip"
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
  build:
    commands:
      - echo "Running Terraform plan..."
      - terraform plan -out=tfplan
  post_build:
    commands:
      - echo "Applying Terraform changes..."
      - terraform apply -auto-approve tfplan
artifacts:
  files:
    - tfplan